# Generated by Django 5.0 on 2023-12-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_category", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_recipe", models.ImageField(upload_to="img_recipe")),
                ("name_recipe", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
                ("cooking_process", models.TextField()),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprofile_app.category",
                    ),
                ),
            ],
        ),
    ]
